# Site settings
title: Medar's blog
header-img: img/home-bg.jpg
email: medar.lol@gmail.com
description: "No description"
baseurl: ""
url: "http://medar.pp.ua"
#twitter_username: SBootstrap
github_username: medvedar 
facebook_username: medar 

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
